version: 2
jobs:
  build:
    step:
      test:
        override:    
          - mocha
      deployment:
        dockerhub:
          branch: master
          commands:
            - $DOCKER_HUB_TRIGGER




